### ISSUE TITLE
Support for Draw/Text created via the PDF tools to save to pdf

### ISSUE THREAD

**Issue by PsyberSouL** [farling42/fvtt-pdf-pager#103]
I noticed there are text and drawing tools on the pdf tool bar that allows for viewers to draw or add text where there are no fillable text fields but any drawings or text added this way doesn't save to the document when closed and reopened. 

I'm not sure if it's possible but could there be a toggle made to allow people to save drawings or text added via the pdf toolbar to the document? Ideally I'd like to be able to allow players to draw on the pdf the path they are taking to get to their destination and add text for landmarks they came across as per rules for Journey phase in The One Ring ttrpg 2nd edition.

![image](https://github.com/farling42/fvtt-pdf-pager/assets/27891102/a1a6893d-50cb-413f-b7ae-51898186a0b6)

**Comment by farling42** [comment]
I am not seeing those controls in the top-right corner of the PDF viewer.
Which version of Foundry, and which browser are you using?

**Comment by farling42** [comment]
I see the controls in Foundry V11, but they are hidden in Foundry V12.

**Comment by PsyberSouL** [comment]
I'm using Foundry V11.315 (latest and probably last build for V11) and Chrome Version 126.0.6478.127 (Official Build) (64-bit).

I'm currently having to make do with creating scenes of the Journey entry sheets to allow players to draw their path and then saving a screenshot of it to add to their journal. It'd be a huge benefit if we could use your module to draw on the pdfs and have the drawings saved.

This is what we did before:
![image](https://github.com/farling42/fvtt-pdf-pager/assets/27891102/004e64dc-237f-4f75-a941-efc910160a8d)

**Comment by farling42** [comment]
16 hours so far. Almost there (possibly).

**Comment by farling42** [comment]
This should be available and working in V1.1.0  (after a further 6 hours of work).
