### ISSUE TITLE
File origin does not match the viewer's

### ISSUE THREAD

**Issue by Babayushki** [farling42/fvtt-pdf-pager#106]
Foundry Version 11 (build 315 | stable)
World System: Custom System Builder 3.2.5
Browser: Google Chrome Version 126.0.6478.127 (Official Build) (64-bit)

No installed modules are conflicting with PDFpager.

I get the following console errors when trying to view PDFs while the module is enabled:
![Screenshot 2024-07-14 022018](https://github.com/user-attachments/assets/bc365768-8b0f-4ac5-92a2-f7d89fcfa41f)

I do not have any problems with viewing PDFs when the module is disabled. I saw in the releases "Use legacy-dist version of pdfjs to support older Foundry/Browsers", but I do not know how to do so.

**Comment by farling42** [comment]
Which specific version of the module are you using?

**Comment by Babayushki** [comment]
I'm using version 1.1.1

**Comment by farling42** [comment]
What is the URL you've set for the PDF file?

It seems that this error is being reported because there is a difference between the URL of the PDF browser window address and the URL of the PDF document itself.

**Comment by Babayushki** [comment]
I'm not sure to be honest. I'm not tech-literate.

To give some additional details/context:

- The PDF is a character sheet which was created using PDFium. I edited the PDF in Adobe Acrobat to make it form fillable. 
        -  In Adobe Acrobat's document properties, it says the PDF has no base URL. 
- I'm using **The Forge** to host. I uploaded the document to a folder in my asset library. 
- I can view PDFs in Journals; I **cannot** view them when using them as character sheets for actors. When attempting to open an actor, the sheet doesn't load. 

![Screenshot 2024-07-14 032427](https://github.com/user-attachments/assets/2fb2ff49-d031-49cf-be12-be485bf628df)
Actor is on the Left; Journal is on the Right.

**Comment by farling42** [comment]
Could you try version 1.1.2?

I checked what changes the Foundry team made in the PDF.JS library, and they specifically removed the check that would generate the error that you saw.
I have made a similar change in the PDFJS library in PDF Pager, so hopefully it will be working properly.

**Comment by Babayushki** [comment]
That seems to have worked. Thank you very much! I don't have much to give, but I'll drop a tip for you.

Cheers!

**Comment by farling42** [comment]
Many thanks for the donation!  :-)
