### ISSUE TITLE
Annotating not shared or saved, prevents game world being shut down/reloaded while pdf is open

### ISSUE THREAD

**Issue by 4m2c4bl3** [farling42/fvtt-pdf-pager#107]
I am sure to de-select the annotation tool, but none of the data saves. When annotating from a browser window and going to navigate away, it gives me 'unsaved changes will be lost' warnings. When annotating from the main foundry vtt client, trying to reload app or return to setup or even exit does nothing, until I close the pdf.

![image](https://github.com/user-attachments/assets/d9237b0e-4850-41ae-96d0-9d92923ca86b)

**Comment by farling42** [comment]
Which version of Foundry?
Are any errors reported in the browser Console (can be opened with F12)?

**Comment by 4m2c4bl3** [comment]
V12, and nope. 

https://github.com/user-attachments/assets/2faf0a4d-8949-4df2-b4b3-6c55eba075fd

**Comment by farling42** [comment]
In the console, could you enter the following which should provide some debug in the console, so that I can see what is happening (or not) with your installation - and then repeat the above steps.

```
CONFIG.debug.pdfpager=true
```

**Comment by farling42** [comment]
Ah, also which game system are you using?

**Comment by farling42** [comment]
I've just noticed that it is possible to edit even if the user has only Observer rather than Owner permission on the document.

**Comment by 4m2c4bl3** [comment]
I'm using this system: https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima 

with debugging on, i'm not seeing anything new
![image](https://github.com/user-attachments/assets/f802b1a9-7eec-4a2a-904b-9376320e9f99)

**Comment by farling42** [comment]
I don't know if this is the cause, but I've just created version 1.1.5 which will prevent non-OWNERs from being able to add annotations to PDF pages.

**Comment by 4m2c4bl3** [comment]
thanks, i'll give it a try.

**Comment by 4m2c4bl3** [comment]
observer role is still able to see/use editing tools in 1.1.5, and the behavior remains the same for the owner. i'm going to try and create a new game world with no other addons to see if there's something else conflicting.

i made a new world with only the system and PDF-pager, and i finally am seeing an error message.

![image](https://github.com/user-attachments/assets/d98fa2ea-d86d-46f7-b35e-7ddb2076522b)
this didn't come back when i cleaned the console, but i caught it once.


https://github.com/user-attachments/assets/2d481eeb-4c72-4d29-89e5-648a595667f3

**Comment by farling42** [comment]
That error about a missing file is unavoidable. It just means that the module doesn't ship with any predefined mappings for your game system. I am still trying to find how to stop it from being reported.

**Comment by farling42** [comment]
Could you give me a screen shot of this module's settings in your foundry please.

**Comment by farling42** [comment]
Also, does it occur with all other modules disabled (other than pdf-pager and libWrapper)?

I've now got Fabula Ultima game installed on Foundry 12, but I'm running Chrome rather than the app, and everything seems to be working.

**Comment by farling42** [comment]
I've just noticed that annotations aren't saved if "Support Form-Fillable PDFs" is not enabled.

**Comment by farling42** [comment]
Version 1.1.6 will save annotations when "Support Form-Fillable PDFs" is not enabled (as well as when it is enabled).

**Comment by 4m2c4bl3** [comment]
> I've just noticed that annotations aren't saved if "Support Form-Fillable PDFs" is not enabled.

That was it!! Thanks :)
