### ISSUE TITLE
request: override default settings per journal page

### ISSUE THREAD

**Issue by 4m2c4bl3** [farling42/fvtt-pdf-pager#108]
I'd love a way in each journal page to set default zoom/zoom percentage/spread/scroll for that specific page. Most of my PDFs work as even spread, but a few need to be odd spread, so anyone who wants to look at them needs to manually change that when they open it, etc.

**Comment by farling42** [comment]
Spread has been added in version 1.2.0

**Comment by 4m2c4bl3** [comment]
uh, i can no longer edit pdfs now after the new update. if i forcibly show the edit buttons the edits work/save, but they're hidden by default. i didn't change anything else in the settings 😅 
it seems it never goes into the setupAnnotations function?

**Comment by farling42** [comment]
Took me a little while to find the issue...

With an editable PDF, the annotation tools are not displayed in the PDF viewer menu bar.

**Comment by farling42** [comment]
Lack of annotation tools fixed in 1.2.1

**Comment by 4m2c4bl3** [comment]
everything seems to be working now. thank you again!
