### ISSUE TITLE
FIllable PDF Sheet doesn't save changes

### ISSUE THREAD

**Issue by eldritchkermit** [farling42/fvtt-pdf-pager#109]
I am on v12, using Simple Worldbuilding since Vagabond, the system I want to run, doesn't have a system yet. I have the fillable pdf set for the Actor sheet, but unfortunately any edits I make to actors using that PDF sheet do not seem to save, I am not sure as to what might be causing this.

**Comment by farling42** [comment]
What version of Foundry, Simple Worldbuilding and the module are you using (specific numbers please).

**Comment by eldritchkermit** [comment]
![image](https://github.com/user-attachments/assets/7a0809f1-533f-4059-ba7a-1f3d77e465e6)
![image](https://github.com/user-attachments/assets/a0171ff0-f4b1-4ea7-9920-e425b506e72e)

These are the versions I'm using.

**Comment by farling42** [comment]
I tested with a fillable PDF sheet I found online called "VAGABOND - Hero Record.pdf" and it is all working as expected.

If that isn't the correct PDF, would you be able to provide me with the relevant PDF?

Could you also provide the module settings for PDF Pager. I had used the default settings when testing with the above PDF.

**Comment by eldritchkermit** [comment]
Sure, this is the version of the Hero Record I'm using:

[Vagabond - Hero Record v15 (Form-Fillable).pdf](https://github.com/user-attachments/files/16377298/Vagabond.-.Hero.Record.v15.Form-Fillable.pdf)


And these are the settings for PDF Pager that I am using:

![image](https://github.com/user-attachments/assets/32abc97c-702a-4093-922a-9cf64dbef17b)

![image](https://github.com/user-attachments/assets/d2fd89d9-25b3-4e9b-94c8-a40dc06d7efd)

![image](https://github.com/user-attachments/assets/7154a0ec-8723-4b9c-8e1b-12856a03d094)

I'm not sure since this is my first time using the module, but maybe I messed up something in the settings?

**Comment by farling42** [comment]
In the "Field Mappings for Actors", can you replace your current text with the following:
```
{"Hero Name":"name"}
```

Also, untick "Show Mapping Tooltips".

Although it won't fix anything, it will check that the module is working. The Hero Name on the PDF sheet should be replaced with the name of the Actor that you're displaying in the PDF.

**Comment by eldritchkermit** [comment]
![image](https://github.com/user-attachments/assets/128fcebc-dbfa-424d-8e5f-0d794f73b25b)

Done, I'm not sure if the name is displaying at all though.

**Comment by farling42** [comment]
Oh, for the V1.5 sheet the syntax would be:
```
{"Name":"name"}
```

Could you open your browser window (F12 on windows 11), and look to see if any errors are being reported.

**Comment by farling42** [comment]
I'm able to edit the attribute fields in the PDF, and that information gets saved.

If I edit any of the skill checks, then they get replaced as soon as I tab out of the field (because they are automatically calculated, and really should have been marked as read-only within the PDF itself).

**Comment by farling42** [comment]
This is what my test looks like after closing and reopening the changed Actor sheet:

![image](https://github.com/user-attachments/assets/75944060-34d2-470c-af13-201a6ef3a28e)

**Comment by farling42** [comment]
On opening that panel in your browser, can you click on the "Console" at the top, just to the right of "Elements".
This might list some errors.

**Comment by eldritchkermit** [comment]
![image](https://github.com/user-attachments/assets/bd7d2e60-8e03-422f-b944-c5b20bff771a)

**Comment by farling42** [comment]
I don't know why it is there, but can you delete "system.bonuses" from the text search box in your "Console" panel.

**Comment by eldritchkermit** [comment]
![image](https://github.com/user-attachments/assets/91742494-69e9-4627-81f2-86afb6685763)

![image](https://github.com/user-attachments/assets/751a48fe-7520-45a9-9bf3-1c30d7cfe17b)

The second error is just the result of a misclick on my part, a warning about the screen resolution since I had accidentally shrunk the Foundry browser window.

**Comment by farling42** [comment]
At the top of the Console panel, can you change "Default Levels" to "All Levels" and then open the PDF sheet and try making some changes. It should report each change that you make.

**Comment by eldritchkermit** [comment]
![image](https://github.com/user-attachments/assets/2ee96781-06bf-44f7-a176-b01a3324dd12)

**Comment by farling42** [comment]
That looks good. All those messages about "Hiding value..." indicate that the text you are typing in is being saved on the associated actor.
Do more log entries appear when you type text into any of the PDF fields?

**Comment by eldritchkermit** [comment]
Ok, so, I opened it up and it seemed like it had saved my previous changes, but then I tried to add another change, closed it and opened it up again and it reset back to the default version of the pdf, for some reason.

![image](https://github.com/user-attachments/assets/11facfec-5136-4c5e-98d1-77c22f1d5b63)

This is what the console showed me.

**Comment by farling42** [comment]
There's a lot of automation built into the PDF document, which might also cause some issues.

It might be worth marking some fields as read-only within PDF Pager so that PDF pager doesn't try to modify them when the rules inside the PDF are also trying to change some values.
