### ISSUE TITLE
@PDF does not open the specified page

### ISSUE THREAD

**Issue by af-dpe** [farling42/fvtt-pdf-pager#111]
Using "(@PDF[RG|page=112]{see p. 112}" always opens the last opened page of the PDF (RG) but does not jump to page 112.

The error currently only exists in this one PDF. Cloning the PDF meant that it worked with a new parameter (RG2). After deleting the original and renaming the copy, the error was there again.

The jump always takes place to the last page that was opened in the PDF via the Item (see screenshot) button.
![grafik](https://github.com/user-attachments/assets/8be4fbec-3f2a-4271-af32-d4d73e2b4e07)

For other PDFs the command works without any problems.

**Comment by farling42** [comment]
Could you open the journal page that contains your PDF link, and check with the "<>" editor button that there is no hidden HTML formatting within the text of the link.

As a side-note, a user on github has the account name pdf, so prefers any reference to be inside the "back-tick" quotation marks, such as `@pdf`

**Comment by Thogrim1984** [comment]
Hi,

I am the other SL in the campaign.

There are no HTML tags in the expression.

And strictly speaking, the link does not lead to the page indicated at the top of the item (sr5 ruleset), but simply to the last open page in the PDF or the title page.

**Comment by farling42** [comment]
Which version of foundry, game system (name + version), and version of the PDF Pager module?

Are these links in a normal journal page, or in a special place on the page which has special handling for PDF pages?

**Comment by farling42** [comment]
If you know how to use the Element Inspector in your browser, could you look at the element containing the PDF link, and see if it contains both `data-hash` and `data-uuid` as seen in the following image:
![image](https://github.com/user-attachments/assets/14381fac-faa6-4d4e-abfa-9de3c8b85c55)

**Comment by Thogrim1984** [comment]
Hi,

Versions:
Foundry: V11 Stable - Patch 13 (Build 315)
Game System: Shadowrun 5th Edition 0.21.0
PDF-Pager: 1.2.1

"Are these links in a normal journal page, or in a special place on the page which has special handling for PDF pages?"

The link in the picture and the "problem link" are two different things.

The link in the image is the implementation of the PDF pager module directly as a dependency of the SR5 rulesets and is therefore directly anchored in the system.

The link in the item description is the one mentioned by "`@pdf[RG|page=112]{see p. 112}`". And here is the problem.

Here is another image of the entire item with both PDF links:

![image](https://github.com/user-attachments/assets/50c1aecd-0780-47d5-8597-3cf72e534fdc)

Here is the HTML-Element:

`<a class="content-link" draggable="true" data-hash="page=112" data-uuid="JournalEntry.QfGvtyO4zz2zuTwD.JournalEntryPage.MTtRO9F7EPCH7O32" data-id="MTtRO9F7EPCH7O32" data-type="JournalEntryPage" data-tooltip="PDF Seite"><i class="fas fa-file-pdf"></i>siehe S. 112</a>`

And here ist the entire paragraph:

`<p>Die Verwendung einer Garotte setzt einen erfolgreichen Angriff voraus, um die Waffe in Position zu bringen, ähnlich einem Festhalteangriff. Der Angreifer verwendet seine Fertigkeit Exotische Nahkampfwaffe (Garrotte), um das Festhalten durchzuführen. Der Angriff muss mit dem Modifikator für die Trefferzone des angesagten Ziels (<a class="content-link" draggable="true" data-hash="page=112" data-uuid="JournalEntry.QfGvtyO4zz2zuTwD.JournalEntryPage.MTtRO9F7EPCH7O32" data-id="MTtRO9F7EPCH7O32" data-type="JournalEntryPage" data-tooltip="PDF Seite"><i class="fas fa-file-pdf"></i>siehe S. 112</a><span class="markedContent" id="page32901R_mcid6817">)</span> durchgeführt werden und mindestens einen Nettoerfolg erzielen. Sobald die Waffe in Position gebracht worden ist, kann der Angreifer in seiner nächsten Handlungsphase den Schaden der Waffe verursachen und gleichzeitig seinen Griff mit einer weiteren Angriffsprobe verbessern oder das Ziel niederschlagen.</p>`

I don't know if the red span element around the closing parenthesis could have anything to do with it, it's definitely reinserted by Foundry after I explicitly deleted it, but it's also outside the PDF command ...

**Comment by farling42** [comment]
Can I just check that you are using `@PDF` and not `@pdf` since the PDF Pager module only works with upper case.

**Comment by Thogrim1984** [comment]
Ok, I found the module that causes the error and I really didn't expect that in this context ... I had disabled all modules that do anything with the journals in advance, but after checking the console I just ran Find the Culprit again... The module, after deactivating it, works again: 

https://foundryvtt.com/packages/touch-vtt

I don't know if this will help you with general bugfixing, for us it should work without Touch VTT. But I'm still happy to help with troubleshooting.

**Comment by farling42** [comment]
Ah, it's good that you found the issue.

I suspect it is the "fake touch" that TouchVTT is doing which is ignoring the `data-hash` field of the link.

It would be interesting to see if linking to a heading within a normal text journal page also fails to be displayed to open the page at that heading when TouchVTT is used.

**Comment by Thogrim1984** [comment]
Can you replicate the error in your system? Or is this a crazy ours problem?

**Comment by Thogrim1984** [comment]
But in general:

We have never had any problems with linking to journals, whether to PDFs (which we use intensively) or to individual journal pages (which we also use, but not so often). Only this link to the PDF with this abbreviation causes problems.

Perhaps also relevant: We use Forge as a host.

**Comment by farling42** [comment]
I wonder if "RG" is used anywhere else, such as an actual journal document name or as the PDF code for another page?

**Comment by Thogrim1984** [comment]
I would say "no". But I'll look through everything again tomorrow. It's too late for that kind of detective work today :D

**Comment by Thogrim1984** [comment]
I have now gone through all our journals. No, RG is only used once, no PDF and no journal page uses that except the PDF in question.

**Comment by farling42** [comment]
I will be GMing for the evening.  It seems strange that it only occurs on one particular PDF with a particular code.

**Comment by farling42** [comment]
With Touch VTT enabled on my desktop (which doesn't have a touch screen):

![image](https://github.com/user-attachments/assets/f18b3e2d-7e00-4e7b-b84e-581c9cf6ee0f)

With Touch VTT module disabled:

![image](https://github.com/user-attachments/assets/7346fab7-5d2b-4da8-91ca-d0d91b69c044)

**Comment by farling42** [comment]
The callback on the "a" link has `event.currentTarget` pointing to the "a" element.

When the TouchVTT module is enabled, `event.currentTarget` is pointing to the "div" of the Journal window (not even the page).

**Comment by farling42** [comment]
I've raised an issue on the touch-vtt module, since it is creating an event with the wrong information.

**Comment by farling42** [comment]
Closing this issue now as it is a problem with touch-vtt.

**Comment by farling42** [comment]
Issue has been fixed in Touch VTT version 2.2.2
