### ISSUE TITLE
Images added are selected for editing when PDF is reopened.

### ISSUE THREAD

**Issue by 4m2c4bl3** [farling42/fvtt-pdf-pager#112]
This persists across even restarting the server/people's pcs. It is there both for people who have permission to edit images, and for people who do not. Foundry v12.330

![image](https://github.com/user-attachments/assets/5b4ffeb0-5337-4c7c-9be5-06124ba82eb4)
![image](https://github.com/user-attachments/assets/cb506528-faa9-42c4-82ad-a8540757f0de)

![image](https://github.com/user-attachments/assets/97d565de-17b0-493c-acd5-6abb9921450f)

**Comment by farling42** [comment]
Those are annotations which are present in the PDF being displayed.

All users will be able to see them, but only the owner of the PDF will be able to modify/delete them.

The included console log shows warnings from the Ownership Viewer, which are not relevant to this issue.

**Comment by 4m2c4bl3** [comment]
The issue isn't that the annotations are showing up, it's that one is always selected. The delete button/etc options are always there for everyone, and the second screenshot account (with no editing permissions, see there aren't the options to edit in the top right hand side) CAN hit those buttons and move/delete/etc the image.

**Comment by farling42** [comment]
Can you tell me the version of Foundry, PDF Pager, and the game system and it's version please.

In my Foundry V12 installation, a user without edit permission on the document does not see the edit annotation controls.

**Comment by 4m2c4bl3** [comment]
foundry v 12.330, chrome, PDF pager latest version (1.4.0), on Chrome. I noticed the issue in the previous version as well, just haven't had time to make a report. System is[ project-fu ](https://github.com/League-of-Fabulous-Developers/FoundryVTT-Fabula-Ultima).

Also since the last time it was an issue based on the config options, here's my PDF pager config options:

![image](https://github.com/user-attachments/assets/2ce74ae2-2854-401b-9ae8-aec456fc47d0)
![image](https://github.com/user-attachments/assets/57c6a07e-da4e-47db-98ad-95e165805939)


Example of the weird semi-fake-strange permissions the users have is below.
https://github.com/user-attachments/assets/4b8735f4-6223-47fc-8f5a-d5d25c781ec9

**Comment by 4m2c4bl3** [comment]
Also for the ownership, they don't have the options to edit, which I understand indicates ownership vs not. 
![image](https://github.com/user-attachments/assets/b8d680c1-5e28-4978-9624-1758bf640553)
I did double check using an extension, they should only have Observer permission.
Journal Permissions:
![image](https://github.com/user-attachments/assets/f7204f4e-62a6-47d2-a3a9-83ef20842b81)
Page Permissions:
![image](https://github.com/user-attachments/assets/9d42e6aa-4044-48bc-a9cc-86e51fb78d9f)

**Comment by farling42** [comment]
Are you using anything like Monk's Enhanced Journal, or some other module that wraps the default JournalEntry sheet?

**Comment by farling42** [comment]
Could you try version 1.4.1 to see if that fixes the problem. I have changed how I determine if a PDF is editable.

**Comment by 4m2c4bl3** [comment]
sorry for the delay in replies. i don't think i'm using anything that affects journals at all. i'll set up an environment again that's just the core system and pdf-pager. the issue is still there. i don't even know if it's a permissions thing, because when i load the pdfs on my gm account, before i enable editing, it also can move the image around and has it selected when i scroll to the page.

**Comment by 4m2c4bl3** [comment]
i figured out what causes it! if you copy paste an image you already inserted, the behavior happens.

**Comment by farling42** [comment]
Ah, thanks for finding how to reproduce the issue. I will look into it later.

**Comment by farling42** [comment]
I've managed to reproduce the issue, and it is related to having multiple images (PDF calls them "stamps") as annotations.

Hopefully version 1.4.2 will improve the handling for stamps, so that the editor controls don't remain on display.

**Comment by 4m2c4bl3** [comment]
the editor controls are visible for a moment, but then they disappear. good enough for my players and me, thank you again!
