### ISSUE TITLE
Some fields won't save inputs

### ISSUE THREAD

**Issue by Orionox** [farling42/fvtt-pdf-pager#113]
I'm using a pdf as a character sheet and some of the fields won't save inputs, but others will and I don't see any discernable difference

**Comment by farling42** [comment]
Are you able to tell the version of Foundry, the game system and its version, a copy of the fillable PDF and the fields which won't save?

If you are computer-literate, then you could open your browser's console window (F12) and enter the command "CONFIG.debug.pdfpager=true" and see what is reported when you try to enter data into the various fields.

**Comment by farling42** [comment]
I think I've found the problem. It is to do with your PDF being not having any internal calculations inside it.
I think I may have seen this issue before.

Version 1.4.3 hopefully fixes this problem for you, whilst still working for other players too :-)
