### ISSUE TITLE
util.isDate is not a function

### ISSUE THREAD

**Issue by johnweland** [farling42/fvtt-pdf-pager#117]
Using this with Foundry VTT v12 331 on the main scree where module warning and errors are shown. PDF Pager has an issue "util.isDate is not a function"

**Comment by farling42** [comment]
I've seen this same error reported on the Foundry Discord from a couple of other modules too.

I don't know what is causing it, but it is not generated by the pdf-pager module (it does not call any function called `isDate`.

Can you tell me the game system you are using, and it's version.
Also can you provide a screen grab of the entire error stack reported in your browser's console.

**Comment by johnweland** [comment]
yeah its weird I just opened the repo in my IDE and did a global search and as you say there is no call to an .isDate function.

I am seeing there error in the foundry main page before entering any world. that said `DnD 5e 4.4.1` and `PDF Pager v1.5.3`
<img width="1680" alt="Screenshot 2024-11-16 at 9 00 21 AM" src="https://github.com/user-attachments/assets/8024226f-70b1-4308-9925-9b54d1d92e0d">


I'll try to get a screenshot of the console in a few minutes.

**Comment by farling42** [comment]
Ah, I think that is where it was reported on Discord too.
For some reason, the core Foundry is generating that error, but nobody has reported why it is being generated.

**Comment by farling42** [comment]
Hi, can you update the Foundry issue with the requested details please.
https://github.com/foundryvtt/foundryvtt/issues/11808

**Comment by farling42** [comment]
As reported in the Foundry VTT issue, the problem is caused by using Node v23, which Foundry does not yet support. Downgrade to v22 and everything should be fine.

(This is primarily to close down this issue with the known fix.)
