### ISSUE TITLE
[Bug?] PDF fillable wont save

### ISSUE THREAD

**Issue by Fyrexian** [farling42/fvtt-pdf-pager#19]
Module Version: v0.16.2

Describe the bug
I downloaded this module to use the pdf fillable feature and it worked 2 weeks ago(?)-ish and saved the information. Now it doesn't, but it remembers the old info before this feature started to fail.

Copy actor id
edit pdf and put actor id into pdf code

Expected behavior
To save the fillable boxes

Foundry Version: 10.286

Game System: PF2e 4.2.3

Additional context
https://user-images.githubusercontent.com/47077661/194621590-bf811d0f-382d-4879-b8c2-cce8f2f6af3b.mp4
![image](https://user-images.githubusercontent.com/47077661/194627318-2b0922a0-9bc4-49ee-bb73-08d1facd8097.png)

**Comment by farling42** [comment]
Hi, I have been unable to reproduce this so far.

In the console, can you set the reporting level to "All Levels" and then it should report something like the following when an edit is made in the field (at least when focus is lost on the field).

```
pdf-pager: unmapped PDF field: NAME 'Pronouns' ID '698R', = 'new'
pdf-editable.mjs:120 Storing hidden value on 'Martin': 'Pronouns' = 'new'
```

**Comment by Fyrexian** [comment]
I only see this when I open it and no other reports appear after that.

![image](https://user-images.githubusercontent.com/47077661/194682257-beb3951d-2744-4a89-bfa4-3b4f50a4f51c.png)

**Comment by farling42** [comment]
I've found a PDF for the academy sheet, but failed to find one that is fillable. Do you have a link to where I can get a copy?

When I'm using other fillable PDFs (like the PF2 character sheet) then everything seems to work OK (Foundry 10.287, PF2 v4.2.4)

(The PF2 character sheet generates error reports from the pdf_scripting_manager.js inside pdf.js, but the form still appears to work.)

**Comment by Fyrexian** [comment]
Yeah there wasn't any fillable version of it, so I made the copy myself.

[Academy Sheet_2.pdf](https://github.com/farling42/fvtt-pdf-pager/files/9742632/Academy.Sheet_2.pdf)

**Comment by farling42** [comment]
Version 0.17.0 contains support for PDFs which don't have PDF event handlers in them.
