### ISSUE TITLE
PDF forms / form fields are shown

### ISSUE THREAD

**Issue by CePeU** [farling42/fvtt-pdf-pager#22]
On most PDF readers form fields are highlighted, while this is great for input it is not so nice for reading. I found at least one PDF reader which does not highlight form fields. Could it be made optional that form fields are shown or ignored? Preferably with a toggle switch. That way input could be done assisted with highlighting and normal play could be made without. Idealy the form fields can be normally accessed even if not highlighted.

**Comment by farling42** [comment]
That is a feature of the pdfjs library provided by Foundry, I don't think that I have any control of its presentation.

**Comment by CePeU** [comment]
Are you able to access the level of transparency?

**Comment by farling42** [comment]
In the CSS, there is a variable called `--annotation-unfocused-field-background` which is used for the background of all editable fields.
In viewer.css there `scripts/pdfjs/web/viewer.css`, there is a section

```json
.annotationLayer .textWidgetAnnotation input,
.annotationLayer .textWidgetAnnotation textarea,
.annotationLayer .choiceWidgetAnnotation select,
.annotationLayer .buttonWidgetAnnotation.checkBox input,
.annotationLayer .buttonWidgetAnnotation.radioButton input {
  background-image: var(--annotation-unfocused-field-background);
  border: 0px solid transparent;
  box-sizing: border-box;
  font-size: 9px;
  height: 100%;
  margin: 0;
  padding: 0 3px;
  vertical-align: top;
  width: 100%;
}
```

Remove the `background-image` from that block is enough to remove the blocks that appear.

**Comment by CePeU** [comment]
The last parameter of rgb is transparency if I remember correctly from my studies while learning CSS for foundry. So maybe if you change:
style='fill:rgba(0, 54, 255, 0.13) --> style='fill:rgba(0, 54, 255, 0.0) ?
That way the change would be minimal. As allways ignore me if I talk rubish.

**Comment by farling42** [comment]
I've made a simple update, so this will be available as a module option in version 0.18.0

**Comment by CePeU** [comment]
Thank you :) It drove me nut's that a professional viewer like Acrobat does not seem to allow to customize something like that :). It took some time but I found a reader which ignored it so it seemed optional. I will really like that option in PDF Pager!

**Comment by farling42** [comment]
0.18.0 should be available now.
