### ISSUE TITLE
Bug: Unable to open Purist Sheet in OSE 1.6.7 as character sheet

### ISSUE THREAD

**Issue by justinthejaguar** [farling42/fvtt-pdf-pager#26]
Chrome
node.js
V10.288
Using AAC sheet
https://necroticgnome.com/products/old-school-essentials-purist-character-sheet

Set up the sheet as a character sheet for this sheet, and

File shows corrupt
"PDF.js v2.14.305 (build: eaaa8b4ad)
Message: Invalid PDF structure."

**Comment by farling42** [comment]
If you disable the PDF Pager module, and try to use the PDF with a journal PDF page do you get the same error?

**Comment by farling42** [comment]
I just extracted the Old-School Essentials - Purist Character Sheet v1-2 - AAC.pdf from the zip file in your link, and the file loads perfectly inside Foundry.
Are you sure that the file got uploaded to your Foundry server properly?

**Comment by justinthejaguar** [comment]
> If you disable the PDF Pager module, and try to use the PDF with a journal PDF page do you get the same error?

No. I am able to open the PDF in a journal (even with PDF Pager)



> I just extracted the Old-School Essentials - Purist Character Sheet v1-2 - AAC.pdf from the zip file in your link, and the file loads perfectly inside Foundry.
> Are you sure that the file got uploaded to your Foundry server properly?

-Out of curiosity are you running it in the OSE system. I am wondering if the conflict is the system.
-The file is able to be opened through Samba just fine, so it is uploaded correctly. Here is the error I am receiving.
![image](https://user-images.githubusercontent.com/38022481/195841194-5150a31e-8377-48d8-a209-0f177ceaf7dc.png)

**Comment by justinthejaguar** [comment]
The error appears in the console log for google chrome.

**Comment by farling42** [comment]
I just started up my Node installation and the PDFs are still working.
What do you have in the module settings box labelled "PDF to use for Actor 'character'"
It is probably complaining about the file that has been specified in that box.
I have my PDF at the toplevel of my userdata area, since my field simply contains
`Old-School%20Essentials%20-%20Purist%20Character%20Sheet%20v1-2%20-%20AAC.pdf`

**Comment by farling42** [comment]
The only message I see for viewer.html:1 is
`[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"password" class=​"toolbarField">​ `

**Comment by justinthejaguar** [comment]
I have shut off all extensions in chrome and I still get the same error.
Running Firefox I get the same error.

I have no modules active in the test aside from this one.

Attaching the file sheet from the server.

[Old-School Essentials - Purist Character Sheet v1-2 - AAC.pdf](https://github.com/farling42/fvtt-pdf-pager/files/9788331/Old-School.Essentials.-.Purist.Character.Sheet.v1-2.-.AAC.pdf)


Screenshot of the sheet:
![image](https://user-images.githubusercontent.com/38022481/195897123-4caaafed-1173-44c4-aa96-3b714befc887.png)

**Comment by farling42** [comment]
What do you have in the module settings box labelled "PDF to use for Actor 'character'"?

**Comment by justinthejaguar** [comment]
> What do you have in the module settings box labelled "PDF to use for Actor 'character'"?

Oh my gosh. So obvious. I apologize for wasting your time. I had not filled this field...

**Comment by farling42** [comment]
That's Ok. I am going to put into place something that will prevent being able to change the sheet to "PDF Sheet" if no PDF has been configured. This should prevent other users from encountering this same problem.

**Comment by farling42** [comment]
Version 0.22.0 should prevent this issue happening (for other users) in the future, since the "PDF Sheet" option will only be presented if a PDF has been configured in the module settings.
