### ISSUE TITLE
PDF Links Do Not Observe '!page=nnn' syntax.

### ISSUE THREAD

**Issue by Dick-K** [farling42/fvtt-pdf-pager#29]
If I create a link from a PDF _that I have opened at (eg) page 10_, the link created specifies:

```
@PDF[JournalName#PageName|page=10]{PageLink}
```

...which looks correct and opens the pdf at page 10.

However, if I scroll the pdf to (eg) page 20 and then dismiss the pdf, the next time I use the 'page=10', it opens the pdf at page 20.

Similarly, manually editing the 'page=nnn' parameter has no effect on which page at which the pdf is opened. It opens at the last page viewed.

Reproduced with all modules inactive except PDF Pager and libwrapper and across several pdfs..

Edit: Am using Foundry 10.288 and Call of Cthulhu (unofficial) 0.9.1
I wonder if this is an artifact of the Call of Cthulhu (Unofficial) system? The problem does not occur with Simple World Building.

**Comment by farling42** [comment]
See issue https://github.com/farling42/fvtt-pdf-pager/issues/16 which is actually a symptom of a CoC7 system bug that was reported as https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/issues/1273

**Comment by Dick-K** [comment]
Gotcha, thanks for the quick response, apologies for the duplication.

**Comment by farling42** [comment]
Fixed in coc7 system version 0.9.2
