### ISSUE TITLE
Old @PDF links used a key instead of name broken.

### ISSUE THREAD

**Issue by SalieriC** [farling42/fvtt-pdf-pager#36]
Overall this module is a live saver. Unfortunately, my old @PDF links are broken. They used an abbreviation that you were able to set in PDFoundry, instead of the full name of the PDFs journal document. Here is an example:
```
@PDF[HRE1|page=4]{Hellfrost Rassilon Expansion 1}
@PDF[Hellfrost Rassilon Expansion 1|page=4]{Hellfrost Rassilon Expansion 1}
```

The first link is how it was placed earlier by PDFoundry, the second one in as it is expected now by PDF Pager. The abbreviation is ofc something that isn't used in PDF Pager but the journals still contain the flags from PDFoundry:
![image](https://user-images.githubusercontent.com/1230041/200185929-e1e7d6c1-c96c-414b-9d2a-81c7632bb519.png)
Thus the data is still there. I don't know whether or not the link updater takes this into account but if not I suggest that it should. It would also be nice if PDF Pager could take the abbreviation into account.

**Comment by farling42** [comment]
Ah, I wasn't sure if anybody was using that particular syntax.
I will incorporate it into the next release.

**Comment by farling42** [comment]
Version 0.31.0 adds support for:
`@PDF[pdfcode]{label}`
`@PDF[pdfcode|page=xx]{label}`

**Comment by farling42** [comment]
Note that PDF Pager already supported the use of "PDF Code", but this was previously only used in PDF Pager with the `ui.pdfpager.openPDFByCode` function
