### ISSUE TITLE
Window size for PDF Journals

### ISSUE THREAD

**Issue by SalieriC** [farling42/fvtt-pdf-pager#37]
If possible, a feature that automatically renders PDF journals in a vertical size of the maximum and the width in relation to that (assuming no one plays foundry in pivotal mode) would help tremendously in the legibility of PDFs. With the default resolution, PDFs are very hard to read (at least mine are) and the first thing I need to do when opening a PDF is to resize the window to the maximum height possible so that they become somewhat legible.
Would such a feature be possible and in scope of PDF Pager?

**Comment by farling42** [comment]
Are you asking for the journal window to be made as tall as possible when a PDF is opened?

**Comment by SalieriC** [comment]
Yes, that'd be helpful I think. Similar to the way PDFoundry was. If there were a way to remove the journals header as well this would be even better. As I said: I don't know if this is out of scope for this module but it would make PDFs easier to handle without zooming in.

**Comment by farling42** [comment]
A little while ago I added an option to set the default zoom level. This doesn't address the window size problem (which is tricky for me to force), but hopefully makes part of the PDF a little larger and easier to read initially.

**Comment by SalieriC** [comment]
I don't know if a journal can be forced to open with a specific size but if so, a neat way to do it would be to save the last window size as flags when closing and setting that size with that size next time it is opened.

**Comment by farling42** [comment]
> I don't know if a journal can be forced to open with a specific size but if so, a neat way to do it would be to save the last window size as flags when closing and setting that size with that size next time it is opened.

That sounds like a sensible idea. If the size is stored on the Actor, then the window would have to be sized once for each actor that is opened, but probably better than having to resize every time that the Actor window is opened.

**Comment by farling42** [comment]
Version 0.39.0 saves the window size when a fillable PDF is used for Actor Sheets.
I don't know if this is also required for normal journal entries.

**Comment by SalieriC** [comment]
I'd argue it's especially important for regular journal entries. I use a lot of PDFs to have access to the rules which have no official FVTT support and having to resize them every time I log in is a bit tedious. Would much appreciate if you'd do this for journals as well. =)

**Comment by farling42** [comment]
Having the size of journal windows to be saved is a more general issue with Foundry, rather than being specific to PDF Pager.

I'm sure that many users would prefer the default size of their non-PDF journals to be remembered too.
