### ISSUE TITLE
Enhance scope of translation

### ISSUE THREAD

**Issue by CePeU** [farling42/fvtt-pdf-pager#39]
A few fields seem to be missing from the translation file:

![image](https://user-images.githubusercontent.com/115504753/202429760-216923e5-20b7-4008-b388-163684920629.png)

Also the "Custom PDF" Button used to select the aboce dialogue in the header of the window could use a translation string.

**Comment by farling42** [comment]
Translations will be available in 0.34.0 for each of the following parts of the dialog:
- dialog title
- prompt
- hint
- button

**Comment by CePeU** [comment]
I will try to take a look this weekend and to translate what was left missing. Thanks!
