### ISSUE TITLE
[Bug] blinking pdf

### ISSUE THREAD

**Issue by brunocalado** [farling42/fvtt-pdf-pager#42]
Hi,

When I open a pdf it start to blink.

https://user-images.githubusercontent.com/4999783/205438589-b54451b6-5251-46ab-86d2-d72e5c2c8929.mp4

**Comment by farling42** [comment]
Hi,
I would expect it to blink once when you open a PDF for the first time, because it is generating a table of contents.

Would it be possible for you to provide a copy of the PDF to me so that I can do some more thorough debugging?

**Comment by brunocalado** [comment]
> This happen with all PDFs. But, I'll send a bug one.
[CheatSheet.pdf](https://github.com/farling42/fvtt-pdf-pager/files/10146392/CheatSheet.pdf)

**Comment by farling42** [comment]
I just tried the PDF and it seems to be working properly in my installation.

What browser are you using (and version), and what operating system?


Looking in the browser console, I'm seeing a lot of warnings about some data in the PDF header:
```
Warning: Unsupported header type 1885564018 (pclr).
pdf.worker.js:1111 Warning: Unsupported header type 1668112752 (cmap).
```
Did you create the PDF yourself? Do you know what tool created it?

**Comment by farling42** [comment]
One last question.
Does the PDF display properly if you disable the "PDF Pager" module?  (When you will have to press the LOAD PDF button)

**Comment by brunocalado** [comment]
> One last question. Does the PDF display properly if you disable the "PDF Pager" module? (When you will have to press the LOAD PDF button)

Yes. It work well without pager.

**Comment by brunocalado** [comment]
> I just tried the PDF and it seems to be working properly in my installation.
> 
> What browser are you using (and version), and what operating system?
> 
> Looking in the browser console, I'm seeing a lot of warnings about some data in the PDF header:
> 
> ```
> Warning: Unsupported header type 1885564018 (pclr).
> pdf.worker.js:1111 Warning: Unsupported header type 1668112752 (cmap).
> ```
> 
> Did you create the PDF yourself? Do you know what tool created it?

Windows 10
Google Chrome 108.0.5359.95 (oficial) 64 bits and Firefox 107.0.1 (64-bits)
System: SWADE
Module list:
![image](https://user-images.githubusercontent.com/4999783/205529600-2dd576ee-b07b-4c6f-a6b7-b43c2fe96a78.png)

**Comment by brunocalado** [comment]
I tried Find the Culprit
![image](https://user-images.githubusercontent.com/4999783/205529847-a1a6eb83-1bff-4602-ab09-f9e529401255.png)

**Comment by farling42** [comment]
Unfortunately libWrapper is unlikely to actually cause the error - it is more likely several modules which use that library are affecting each other.

I tried loading up most of the modules in your list, and I get a swirling circle for longer with the following modules enabled:
![image](https://user-images.githubusercontent.com/17485384/205646950-a913fa3e-2534-4fc8-9da2-d0e2f0e574b1.png)

**Comment by farling42** [comment]
Can you try disabling custom CSS?
I don't know what changes the CSS might be making to the PDF pages.

**Comment by delegreg** [comment]
I had the same thing. Steps to reproduce : 

1-new world
2-create pdf journal page
3-install pdfpager module
4-try to open journal page
5-blink happens
6-edit page, save
7-doesn't blink anymore

IMHO it comes down to having a pdf page number stored with your journal page entry

**Comment by farling42** [comment]
I would expect it to blink once when you set up a new PDF, because it calculate the journal's table of contents from the Outline inside the PDF (which causes the page to reload when the table of contents is displayed). But after that there shouldn't be a continuous blinking.

**Comment by brunocalado** [comment]
> I had the same thing. Steps to reproduce :
> 
> 1-new world 2-create pdf journal page 3-install pdfpager module 4-try to open journal page 5-blink happens 6-edit page, save 7-doesn't blink anymore
> 
> IMHO it comes down to having a pdf PageOffset stored with your journal page entry

This stops the blink. But, I have several worlds with lots of PDFs. Is it possible to fix this?

https://user-images.githubusercontent.com/4999783/208421317-9763c004-40e6-48d7-a222-7ade99235aaa.mp4

**Comment by farling42** [comment]
> I had the same thing. Steps to reproduce :
> 
> 1-new world 2-create pdf journal page 3-install pdfpager module 4-try to open journal page 5-blink happens 6-edit page, save 7-doesn't blink anymore
> 
> IMHO it comes down to having a pdf PageOffset stored with your journal page entry

When these specific steps are used with a PDF without an outline, and the PDF page has not already been loaded at least once, then the above steps were enough to cause the constant reloading.

Version 0.36.2 should fix this problem (although it seems like a lower level lack of optimisation that really caused the problem - unsetFlag caused the page to load, even if the flag never existed on the document).
