### ISSUE TITLE
[Bug] Page navigation doesn't work correctly

### ISSUE THREAD

**Issue by delegreg** [farling42/fvtt-pdf-pager#45]
Steps to reproduce : 

1-Create journal entry
2-Create first page, using "dummy.pdf", set PageOffset 3
3-Create second page, using same "dummy.pdf", set PageOffset 10
4-Try activating first then second page, then go back to first, the PDF opens correctly, but page navigation doesn't work (file is opened at the last reading position)

This is a hindrance in my use-case (single pdf containing a whole scanned scenario, journal pages are defined to quickly access several locations or monsters/npcs inside the file)

**Comment by farling42** [comment]
Your steps sound like the issue is with the core support for PDFs within Foundry v10, rather than a bug in the extra support that my module provides.

Have you tried using the table of contents that this module provides to navigate within a single PDF document?

**Comment by farling42** [comment]
Another alternative is to create a normal text journal page containing all your links to specific positions within the PDF, then clicking on those links will move the open PDF to the relevant page/section.

**Comment by delegreg** [comment]
Example PDF is an old scanned module, no toc included, but the workflow you proposed (using a text page as a toc) should work. Thanks for that.

I'm not quite sure that the "page number" field on pdf journal pages belongs to core foundry pdf support, but i'm sure you know better than me.

Still seems unintended behavior that a journal page set to open dummy.pdf at page 10 would open said file at page 3 if the file was previously opened at that page. 

Should i open a ticket to core foundry ? What do you think ?

**Comment by delegreg** [comment]
Updated original issue and latest comment to highlight the PageOffset use, hope it helps.

**Comment by delegreg** [comment]
My bad, just a misunderstanding on my part
