### ISSUE TITLE
[Feature Request] Support PDF Page Navigation for Map Pins 

### ISSUE THREAD

**Issue by delegreg** [farling42/fvtt-pdf-pager#46]
Uee Case : 

As a DM, I would like to have map pins that can open a PDF file to a specific page in an otherwises non-indexed PDF file (ie : file without TOC) in order to quickly view reference material for this location.

Thanks for your consideration.

**Comment by farling42** [comment]
Implemented on 0.36.0

**Comment by delegreg** [comment]
Works as intended, thanks a lot
