### ISSUE TITLE
[Feature Request] Default page number on Scene Notes drop

### ISSUE THREAD

**Issue by delegreg** [farling42/fvtt-pdf-pager#47]
Use Case : As A GM, When i drop a Scene Note on the current Scene and the pdf viewer for that note is opened, i would like to have the current pdf viewer page number as a defaut value for the Page Number Scene Note field.

Maybe default to "1" if the PDF file isn't currently opened. 

This would allow me to quickly populate my scene notes and have them open at the appropriate page when needed (ie : browse the pdf file, dropping notes on the scene as you go). 

As an enhancement, using the current TOC chapter name in the viewer used as the default note name would be a bonus for those using indexed PDFs.

Again thanks for your consideration.

**Comment by farling42** [comment]
Implemented in 0.36.1

Note that the default page number will remain blank, so that the PDF will open at the last displayed page.

**Comment by farling42** [comment]
Note that Foundry V10 does not provide the section name when dragging entries out of journals, so this isn't available for use as the note title.

**Comment by delegreg** [comment]
Works like a charm, thanks for your consideration and your reactivity.

Wish all my coders at work were that efficient ;-)

**Comment by farling42** [comment]
If you look at the size of code change on each of these, then you wouldn't be surprised ;-)
