### ISSUE TITLE
Question abound editable pdf

### ISSUE THREAD

**Issue by Fridan99** [farling42/fvtt-pdf-pager#48]
Question. Does the module handle editable pdfs?
I was testing on a pdf imported from pdf foundry, and it doesn't seem to save the editing changes in foundry.

**Comment by farling42** [comment]
Yes, it can handle editable PDFs (sometimes called "form fillable" PDFs).

You can find instructions on the README at https://github.com/farling42/fvtt-pdf-pager#pdf-character-sheets
