### ISSUE TITLE
[Bug] Frame fields

### ISSUE THREAD

**Issue by Gabryel666** [farling42/fvtt-pdf-pager#50]
Hi and thx for this so nice module !

A report here a visual bug.

When using the option to hide the highlighting of form fields, they disappear well.
But the frame around the fields is still visible while in the original pdf it is invisible.

**Original (create with Foxit Phantom)**

With option higlighting
<img width="252" alt="image" src="https://user-images.githubusercontent.com/65908230/221360826-2ba9f053-b64c-4c52-a470-0898a4b156cf.png">

Without
<img width="239" alt="image" src="https://user-images.githubusercontent.com/65908230/221360806-6f4efd9b-97a0-491d-94a3-8734e3726e0c.png">

**Pdf pager**
Into foundry
<img width="188" alt="image" src="https://user-images.githubusercontent.com/65908230/221360702-9e51f358-8e2e-4e1e-8597-017260b82de9.png">

**Comment by farling42** [comment]
Hi, is it possible for you to provide me with a copy of the PDF, so that I can examine what features I would have to disable in order to hide the surrounding box?

**Comment by Gabryel666** [comment]
Yes, of course.
This is the pdf, create with Foxit Phantom.
[FP1.pdf](https://github.com/farling42/fvtt-pdf-pager/files/10832779/FP1.pdf)

**Comment by farling42** [comment]
Version 0.37.0 has a new option 'Hide Editable Field Border' which will hide the border of editable fields. This can be set separately from the option to hide the filled background.

**Comment by Gabryel666** [comment]
> Version 0.37.0 has a new option 'Hide Editable Field Border' which will hide the border of editable fields. This can be set separately from the option to hide the filled background.

Thx a lot !
