### ISSUE TITLE
Can't enter data on form fillable pdf

### ISSUE THREAD

**Issue by Meliath1742** [farling42/fvtt-pdf-pager#53]
I've created a FF pdf using PDF Escape, uploaded it into the Forge Asset Library and linked it to PDF Pager in Foundry. The pdf is assigned as the CS and shows up when a character is created but it won't allow me to enter any data. I click on the fillable area, its background turns white but no cursor is shown in the editable area and it doesn't see any key strokes I make for the data. A friend of mine says PDF Pager is working for him with no issues. BTW, the pdf works fine outside of Foundry. What am I missing here?? I feel like I'm not installing something correctly...

**Comment by farling42** [comment]
If you open the PDF in a normal journal page (with PDF Pager module disabled) can you edit it there? On 4 Mar 2023 13:20, Meliath1742 ***@***.***> wrote:
I've created a FF pdf using PDF Escape, uploaded it into the Forge Asset Library and linked it to PDF Pager in Foundry. The pdf is assigned as the CS and shows up when a character is created but it won't allow me to enter any data. I click on the fillable area, its background turns white but no cursor is shown in the editable area and it doesn't see any key strokes I make for the data. A friend of mine says PDF Pager is working for him with no issues. BTW, the pdf works fine outside of Foundry. What am I missing here?? I feel like I'm not installing something correctly...

**Comment by Meliath1742** [comment]
Its odd. As a Journal entry PDF and PDF Pager disabled, a few of the fillable areas work, but most do not. I can see the flashing cursor in the fillable areas, but only a few allow me to actually enter data.

**Comment by farling42** [comment]
What browser are you using?
Also, what happens if you open a browser (not containing Foundry) and drag the PDF into it?  (This should use your browser's built-in PDF support)?

**Comment by Meliath1742** [comment]
I'm using Chrome. I'll have to try the pdf-browser and get back with you.

**Comment by farling42** [comment]
It might be worth checking what extensions you have enabled in Chrome - if the PDF is editable on another player's computer.

**Comment by Meliath1742** [comment]
Thanks, I'll check it out.

**Comment by farling42** [comment]
It is also worth checking version 0.39.1 to see if that makes any difference.

**Comment by Simyonovich** [comment]
Yeah, I've tried using Form Fillable pdfs as well. I can edit all the fields, no problem, but I cannot find a way to save the changes, so it always just reverts to the base pdf with none of the information that I added.

**Comment by farling42** [comment]
If you are using PDF Pager and are using a PDF as an Actor sheet, then when you change a field in the fillable PDF the new value is immediately stored on the Actor.

**Comment by Simyonovich** [comment]
I am using PDF Pager and as an Actor sheet. Then I took the time to fill in every field, then closed the actor sheet. I reproduced this bug with several different PDFs in multiple actors. All changes were erased. Tried on both Forge and my local Foundry program, same thing occured. I am going to try removing all other modules, in case there's a conflict.

**Comment by Simyonovich** [comment]
I now tried with a different system from before; Simple World Builder instead of Sandbox and it's now working. interesting.

**Comment by farling42** [comment]
If you open your browser console and switch the logging level to All, then you should see messages appear whenever you modify a value in the PDF. It might be generating an error for the fields which don't appear to be getting saved.

**Comment by farling42** [comment]
Which game system are you using?

**Comment by farling42** [comment]
Closing due to lack of response
