### ISSUE TITLE
Form fillable fields do not use specified font, even if configured in the core settings.

### ISSUE THREAD

**Issue by SalieriC** [farling42/fvtt-pdf-pager#54]
Text type form fields can be set to use a specific font when creating those fields. The PDF reader will then try to use the configured font if found. PDF Pager currently doesn't seem to support this, it defaults to a standard font (Arial I think).It would be nice if the PDF would check if the font is configured on the server (a core setting) and use it if found or use the default if not.

**Comment by farling42** [comment]
Hi, I use the standard PDF library supplied with Foundry V10.  Can you try opening the PDF with the PDF Pager module disabled, and see if editing the files uses the font configured for each field?  If it doesn't work in core Foundry, then perhaps a bug report against Foundry would be a better idea.

**Comment by farling42** [comment]
Another thing to try is simply dragging the PDF into a browser window (a blank window, not one running Foundry). This will show if the browser's PDF plugin uses the editable field fonts properly.

**Comment by SalieriC** [comment]
Tested both, I get the proper font when dragging the PDF to my browser (chromium) but not in FVTT with PDF Pager disabled.

**Comment by farling42** [comment]
> Tested both, I get the proper font when dragging the PDF to my browser (chromium) but not in FVTT with PDF Pager disabled.

Thanks for the test. It definitely seems a bug in core Foundry. It is possible that they aren't using the latest version of the pdf library (the latest version fixes somebody else's issue too).

**Comment by SalieriC** [comment]
Apparently it's an issue with the PDFJS library: https://github.com/foundryvtt/foundryvtt/issues/9054
