### ISSUE TITLE
[Feature Requests]

### ISSUE THREAD

**Issue by friction1** [farling42/fvtt-pdf-pager#58]
1. I wish when I hit a bookmark the view wouldn't change automatically to "page fit" and would stick with the "automatic scaling" that I had chosen in the settings.
2. It would be great to add a bookmark within Foundry instead of doing it in acrobat.
3. It's unclear how to exit presentation mode without quitting the foundry.

**Comment by farling42** [comment]
3 - When I enter Presentation Mode, there is a box that appears at the top of the screen which says that pressing the "ESC" key will exit presentation mode. It works on my chrome browser on Windows 11.

**Comment by farling42** [comment]
2. Unfortunately, the way that information is stored within a PDF does not allow the easy detection of a section header. It would be a lot of work to implement this sort of thing, whereas using the Outline present in the PDF document is a much simpler solution (and is probably quite easy to add using any free PDF editor). Note that you can create links to a specific page within a PDF if that would suffice.

**Comment by farling42** [comment]
1. In the PDF Pager module settings, if "Default Zoom" is set to "None" then the default PDF behaviour will occur without the PDF Pager specifying any specific zoom level (I think that the default behaviour is that the zoom value set within the PDF viewer will be remembered for next time the PDF is opened).  If you set it to something other than "None", then the chosen value will always override the last-set zoom value for a particular PDF.

**Comment by farling42** [comment]
(1) has been fixed in PDF Pager version 0.40.0.   If an explicit zoom is set in the module settings then that will be retained when the PDF is opened from a link to one of the PDF's bookmarks.
