### ISSUE TITLE
Allow drop of PDF page to create @PDF link

### ISSUE THREAD

**Issue by farling42** [farling42/fvtt-pdf-pager#6]
Intercept a drop of a JournalEntryPage that contains a PDF to create a `@PDF` link instead of the usual `@UUID` link.

The created link should be like `@PDF[${codeOrName}|page=1]{${pdfData.name}}`

**Comment by pdf** [comment]
Man I'd really love it if you would use `backticks` around `@pdf` instead of pinging me constantly in this repo....

**Comment by farling42** [comment]
I'll try and remember that :)

**Comment by farling42** [comment]
Possibly intercepting TextEditor::_onDropEditorData
Or TextEditor::getContentLink for JournalEntryPage with a type of 'pdf'

**Comment by farling42** [comment]
JournalEntryPage.prototype.link() creates the actual string.

**Comment by farling42** [comment]
When #9 is implemented, prefer to use the CODE (if defined) rather than the NAME in the link.

**Comment by farling42** [comment]
Implemented in V0.9.0
