### ISSUE TITLE
Resizing Breaks the PDF Sheet

### ISSUE THREAD

**Issue by tomeomei** [farling42/fvtt-pdf-pager#70]
When the actor sheet is set to PDF and someone resizes it, all the text filled in disappears until it goes back to a specific size, which it then appears again. Then we found a new problem where once it does this once, it doesn't allow you to add anymore text to the PDF. If you type anything new it just disappears when you close and reopen the sheet. 

Also the "Hide Editable Field Border" and "Hide Editable Field BG" are checked but it refuses to hide them anymore. 

I have no other modules except for the PDF Pager and required libWrapper. These are all being used on the Simple World-Building game system. They are all up to date as is Foundry.

PDF Pager - v 0.47.0
libWrapper - v 1.12.12.1
Simple World-Building - v 0.8.2
FoundryVTT - v 11.304

**Comment by farling42** [comment]
Hi,
With a new world using the above versions it seems to work properly on my configuration (using a D&D 5E pdf).

Are there any any errors in your browser console during resizing?

Is it possible for you to supply a copy of the PDF sheet for me to investigate with?

**Comment by tomeomei** [comment]
Here is the PDF sheet we were using. I don't see any console errors but I
will mess with it a bit more to see if I can get anything else.

**Comment by farling42** [comment]
The attachment from your email didn't reach the issue on github - I suspect it got filtered out. Could you attach it directly on the web page instead?

https://github.com/farling42/fvtt-pdf-pager/issues/70

**Comment by tomeomei** [comment]
[Icons Character Sheet - fillable.pdf](https://github.com/farling42/fvtt-pdf-pager/files/11941657/Icons.Character.Sheet.-.fillable.pdf)

**Comment by farling42** [comment]
Even with your PDF things seem to be working properly (in the windows app and via chrome browser). So there's something different between our environments.

Which browser and operating system are you using?

Are you using a local installation of the Foundry app?

Is the foundry server hosted locally? If not, where is it located?

**Comment by tomeomei** [comment]
I am using Opera GX but the issue was originally found using the Foundry
app itself which is hosted locally. I am using Windows10, OS
build 19045.3086.

**Comment by farling42** [comment]
Ah, well one problem with Opera GX is that it has had a lot of stuff that Foundry needs stripped out of it. Normal Opera is fine (at least according to the Foundry discord).

Do you have at least 4 GB of free space on your C: drive? (Most likely NOT the problem, but always worth checking to see if it is a browser caching issue.)

**Comment by tomeomei** [comment]
I have more than 4 GB on my C: drive. The issue happened on the Foundry app
itself first, not just OperaGX.

**Comment by farling42** [comment]
Could you send a picture of your module settings, to see if there is a specific combination causing an issue.
My settings are:
![image](https://github.com/farling42/fvtt-pdf-pager/assets/17485384/3dc335cd-43dc-4ef9-9d6e-9c8f2210c95a)

**Comment by farling42** [comment]
Closing since no reply in 3 months.
