### ISSUE TITLE
Miss the option to print the PDF or store the result as PDF file

### ISSUE THREAD

**Issue by yurecz** [farling42/fvtt-pdf-pager#72]
Hello,

Is any way to send the PDF character sheet to the printer or store it as a PDF file on the disk?

Best regards,
Yuri

**Comment by farling42** [comment]
In an older version, the PDF menu bar had a save option, and even now you can press ctrl-S to save a copy of the PDF, unfortunately the form data is not saved as part of that PDF.

**Comment by farling42** [comment]
I need to investigate, since any text entered by the user into the PDF since the window was last opened will appear in the saved PDF when ctrl-S is performed. So the issue seems to be that I'm not putting the data from the Actor into a place where it can be saved in by ctrl-S.

**Comment by farling42** [comment]
Using Ctrl-P to print and Ctrl-S to save a file (while the keyboard focus is in the PDF window) should work properly in version 0.48.1
