### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sirgawain111** [farling42/fvtt-pdf-pager#74]
Foundry version: 11.308
Game system/version: The Dark Eye 5.1.3

Automatically generated section links are broken.

![image](https://github.com/farling42/fvtt-pdf-pager/assets/85822812/21567a03-3241-4f2f-b2ec-071f18ccde98)

![image](https://github.com/farling42/fvtt-pdf-pager/assets/85822812/09ff3457-4d26-4686-bef1-6de201ed3206)

**Comment by farling42** [comment]
Just to check...Is this with a new PDF Page, or did you change the PDF document associated with that page (or replace the PDF file in your user data area)? Regards, MartinOn 11 Sept 2023 20:27, sirgawain111 ***@***.***> wrote:
Foundry version: 11.308
Game system/version: The Dark Eye 5.1.3
Automatically generated section links are broken.

**Comment by sirgawain111** [comment]
It was a completely new PDF page with PDF pager v. 0.48.2.

**Comment by farling42** [comment]
I only have English PDFs, and my Dark Eye rulebook works fine with the table of contents.
I'm wondering if it is that the anchor in the PDF has some german accents on characters.

If you are familiar with using your browser's console, could you put a breakpoint at line 75 in pdf-pager.mjs.
Click in the table of contents, and when the breakpoint is reached, print the value of `pdfsheet.toc`

This should be an object, and if you expand the fields (the triangle symbol), it should be a long list of the possible anchors, which should include something close to the anchor that it is trying to display (which you can see in the `anchor` variable).

---

Alternatively, would I be able to log onto your server to examine the console myself?

Also, what browser are you using on what operating system?

**Comment by sirgawain111** [comment]
We don't have to investigate further, the bookmarks don't work in Acrobat either. So it isn't an issue with PDF pager but an issue with my PDF. Sorry for the false alarm.

**Comment by farling42** [comment]
Ah, it's good to know that my plugin isn't broken.

Good luck with trying to get the publisher to generate a correct outline for the PDF.
