### ISSUE TITLE
[Bug] PDF settings don’t save

### ISSUE THREAD

**Issue by mrkwnzl** [farling42/fvtt-pdf-pager#78]
When I edit the journal page of the PDF, the zoom level isn’t transferred over from the edit sheet to the journal.

Steps to reproduce:

1. Open a PDF.
2. Click “Edit”
3. Change the Zoom level to any other value. It changes in the edit sheet, but not in the journal.

I’m not getting an error message. I tried setting Default Zoom to “none,” and disabling Ignore Zoom in Bookmarks, to no avail.

Foundry Electron App, v11.315
PDF Pager v0.49.0
Cypher System v2.12.0 (although I believe that to be irrelevant, but just in case)

**Comment by mrkwnzl** [comment]
I think this can be generalized. None of the settings for the PDF I set in the PDF edit sheet appear in the journal. Is that by design?

**Comment by farling42** [comment]
I think this is a consequence of any settings you make within the PDF viewer (pdfjs) itself (such as zoom, or choice of page layout) are only stored within that instance of the PDF viewer, they are not read by the PDF Pager module.

**Comment by farling42** [comment]
Although I can investigate to see if it is possible to get (and set) the current state of the pdfjs library and store it as part of the PDF Pager's settings for the PDF.

**Comment by mrkwnzl** [comment]
If it’s not possible, it might be a good idea to have an option to show the control bar on the page.

**Comment by mrkwnzl** [comment]
> See the "Hide PDF Browser Toolbar" module option, which is enabled by default.

🙈 User error. Sorry, I missed that.

**Comment by farling42** [comment]
Closing as won't be adding any additional functionality to save settings which are part of the core pdfjs library.
