### ISSUE TITLE
[Bug] Sidebar appears if it was opened before PDF Pager was enabled

### ISSUE THREAD

**Issue by mrkwnzl** [farling42/fvtt-pdf-pager#79]
When PDF Pager is not enabled, and I open the sidebar in a PDF, and then enable PDF Pager, the sidebar shows up, but without the PDF controls, I can’t disable it. Opening the edit sheet and disabling it there doesn’t save it in the journal. Maybe related to #78?

<img width="977" alt="Screenshot 2023-12-08 at 09 25 53" src="https://github.com/farling42/fvtt-pdf-pager/assets/40534855/02c316e6-0491-4f0a-8f9c-7bfa276c8176">

Foundry Electron App, v11.315
PDF Pager v0.49.0
Cypher System v2.12.0 (although I believe that to be irrelevant, but just in case)

**Comment by farling42** [comment]
In this situation, the presence of the sidebar is stored directly in the browser by the pdfjs library.
In my own testing, using Chrome with any account I get the same situation when opening the PDF, but if I switch to Firefox then the internal sidebar isn't opened.

This is a "feature" of the pdfjs library, which I can't control from outside unfortunately.
