### ISSUE TITLE
[Bug] Uncaught (in promise) TypeError: undefined. Cannot read properties of null (reading 'pdfPage')

### ISSUE THREAD

**Issue by mrkwnzl** [farling42/fvtt-pdf-pager#80]
Sometimes, but not reliably, Im getting the following error when I’m at either end of the PDF and try scrolling even further, for example when I’m at page 1 and try to scroll up.

It doesn’t seem to affect functionality, though.

<img width="501" alt="Screenshot 2023-12-08 at 09 28 41" src="https://github.com/farling42/fvtt-pdf-pager/assets/40534855/0f025191-397f-4b62-a698-5ab5ae9310b5">

Foundry Electron App, v11.315
PDF Pager v0.49.0
Cypher System v2.12.0 (although I believe that to be irrelevant, but just in case)

**Comment by farling42** [comment]
What method are you using to scroll up or down past the start/end of the document?
The methods I've tried:
- using keyboard up/down arrows
- using the mouse middle wheel
- using the arrows in the pdf viewer's scrollbar

**Comment by mrkwnzl** [comment]
Sorry, yes, that should have been in there from the start. I’m using the mouse wheel with high resolution (which sends fractals between 0 and 1 for acceleration instead of actual mouse wheel clicks in pixels in its mouse wheel event). It seems to happen more often when I’m using the momentum feature, where the mouse wheel keeps on rolling after I stop scrolling, sending hundreds, maybe thousands of mouse wheel events.

**Comment by farling42** [comment]
Should be fixed in 0.49.1
