### ISSUE TITLE
Dropdown Menu Bug?

### ISSUE THREAD

**Issue by strlys** [farling42/fvtt-pdf-pager#82]
I’m using a Mr. Gone’s Vampire 3rd edition PDF character sheet ([here's the download link](https://mrgone.rocksolidshells.com/pdf/VtM/VampireRev4-Page_Editable.pdf)), and replacing the character sheet from the WoD v20 system.

So, even when I check the PDF Pager option "Read Fields from PDF", some fields are not read and displayed. In my case, 'dropdown menu fields' are not displayed and are basically blank. This only happens if I write something other than one of the dropdown menu choices, and PDF Pager does not give me the ability to write my own text in these fields, even when I don't have the "Read Fields from PDF" checked.

Here's some demonstration:

Original PDF: 
![image](https://github.com/farling42/fvtt-pdf-pager/assets/75812477/64e870ac-b4a8-4569-a458-2d94ff7c0bd7)

PDF Pager: 
![image](https://github.com/farling42/fvtt-pdf-pager/assets/75812477/282d2f06-562c-48ff-a53d-59f1617bbe86)

Am I doing something wrong, or this is a bug?

Thanks for the awesome module, and I hope you can help me with this!

**Comment by farling42** [comment]
Thanks for the download link. I will need to investigate how the drop-down boxes that also allow manual text input work.

**Comment by farling42** [comment]
Not being able to enter text into the boxes which also provide an optional drop-down menu is a limitation in the pdfjs library which is shipped with Foundry. There's nothing I can do in PDF Foundry to fix this issue.

**Comment by farling42** [comment]
Issue raised on pdf.js library to see if they will implement it.
https://github.com/mozilla/pdf.js/issues/17471

**Comment by develroo** [comment]
> Issue raised on pdf.js library to see if they will implement it. [mozilla/pdf.js#17471](https://github.com/mozilla/pdf.js/issues/17471)
> 
> It was originally raised 5 years ago: [mozilla/pdf.js#10669](https://github.com/mozilla/pdf.js/issues/10669)

Is the Fvtt  pdfjs lib you are using?  

https://github.com/foundryvtt/pdfjs

In which case why is the issue not raised with them directly? There are no issues on that repo far as I can tell?
